export const KNOWN_LZ = [
    'Achille',
    'Achille meadow of Grande Prairie',
    'Aigle',
    'Albatros',
    'Alhambra',
    'Aux Lagnys',
    'Baleine',
    'Billard',
    'Bouche',
    'Bretagne',
    'Bronchite/Renan',
    'Carpe',
    'Cerise',
    'Chamois',
    'Chanet',
    'Coconut',
    'Courgette',
    'Crabe',
    'Crevette',
    'Cuisery airfield',
    'Etoile',
    'Faucon',
    'Feurs-Chambéon airfield',
    'Feytiat',
    'Figue',
    'Francazal airfield',
    'Gide',
    'Grenade',
    'Grippe',
    'Hercule',
    'Indigestion',
    'Junot',
    'La Grange Terrasse',
    'La Prairie',
    'Le Blanc Airfield',
    'Le Blanc airfield',
    'Le Fay airfield',
    'Leontine / Arc en Ciel',
    'Les Lagnys',
    'Lilas',
    'Lièvre',
    'Longeron',
    'Lulli',
    'Marabout',
    'Marguerite/David',
    'Marot',
    'Murene',
    'Orion',
    'Paganini/Hector',
    'Pamplemousse',
    'Peche',
    'Petites Fontaines farm',
    'Planete',
    'Pluto',
    'Poulpe',
    'Rabelais',
    'Reez airfield',
    'Roger',
    'Roi de Cœur',
    'Serin',
    'Signac',
    'Stalingrad',
    'Thalamy',
    'Torticolis',
    'Trellu',
    'Univers / Bouc / Carpe',
    'Univers / Bouc Lieu-dit «\xa0Champs aux moines\xa0»',
    'Vautour',
    'aéroport Feurs-Chambéon',
    'champ de Sainte-Marie',
    'field of Sainte-Marie',
    'les Chanoines',
    'objective: 7 km NW Dizy le Gros',
    'old Airfield'
];
